// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /home/ubuntu/go_1.11.11/go/src/math/bits/export_test.go

//line /home/ubuntu/go_1.11.11/go/src/math/bits/export_test.go:1
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bits

const DeBruijn64 = deBruijn64
